apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugioh-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yugioh-frontend
  template:
    metadata:
      labels:
        app: yugioh-frontend
    spec:
      containers:
        - name: yugioh-frontend
          image: yugioh-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: yugioh-frontend
spec:
  type: NodePort
  selector:
    app: yugioh-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
